from setuptools import setup, find_packages

# # Read the contents of your README file
# with open("README.md", "r", encoding="utf-8") as fh:
#     long_description = fh.read()

setup(
    name="Catalogger",
    version="0.1.0",
    author="Hunter Schweiger",
    author_email="hschweig@ucsc.edu",
    description="Package for loading and analyzing data from HD-MEA recordings based on catalogged metadata.",
    # long_description=long_description,
    long_description_content_type="text/markdown",
    url="git@github.com:hschweiger15/Catalogger.git",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "boto3",
        "botocore",
        "pandas",
        "numpy",
        "requests",
        "s3transfer",
        "pyarrow",
        "tables",
        "scipy",
        "matplotlib",
        "seaborn",
        "h5py",
        "statsmodels",
        "tqdm",
        "joblib",
        "py-cpuinfo",
        "python-dateutil",
        "pytz",
        "redis",
        "smart_open",
        "braingeneers",
        "braingeneers-smart-open",
        "schedule",
        "nptyping",
        "numexpr",
        "pygments",
        "pyqt5",
        "pyqt5-qt5",
        "pyqt5-sip",
        "pillow",
        "xarray",
        "wrapt",
        "zipp",
        "typing-extensions",
        "scienceplots"
    ],
)